name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-24

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get install emacs doxygen graphviz

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/../build -DCPPEMACS_Documentation=ON -DCPPEMACS_Test=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/../build

    - name: Add and push
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "Automation"
        git switch gh-pages
        rm -r *
        rsync -r ${{github.workspace}}/../build/docs/html/* .
        git add -v .
        git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Build Docs" && git push -v
