name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        emacs_version: [25.3, 27.2, 28.2]
        os:
          - ubuntu-latest
          - macos-13 # latest x86_64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: purcell/setup-emacs@v6.0
      with:
        version: ${{ matrix.emacs_version }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCPPEMACS_Documentation=OFF -DCPPEMACS_Test=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
